### ISSUE TITLE
GitHubOAuthToken has an issue with new Personal access token formats

### ISSUE THREAD

**Issue by balasreeni** [symphoniacloud/multi-region-codepipeline#1]
Since new GitHub PAT format is a bit different - I was struggling to execute the pipeline.yaml. Later i figured out that i need to remove the AllowedPattern attribute - post that it worked fine. Thanks for this example.

**Comment by mikebroberts** [comment]
Wow - I'm amazed that was the only thing you needed to change - it's been a long time since I put this together! :) Thanks for letting me know - I've updated the pipeline template.
